"""Create or update .gitignore files for generated projects."""

from __future__ import annotations

import logging

from project_setup_helper.config import ProjectConfig, VENV_DIR_NAME


def ensure_gitignore(config: ProjectConfig) -> None:
    """Create/update .gitignore with Python and venv ignore rules."""
    gitignore = config.project_root / ".gitignore"
    rules = [
        "# Python virtual environments",
        f"{VENV_DIR_NAME}/",
        "venv/",
        "env/",
        "ENV/",
        "",
        "# Python cache/build artifacts",
        "__pycache__/",
        "*.py[cod]",
        "*.egg-info/",
        "build/",
        "dist/",
        "",
        "# Test/type/lint caches",
        ".pytest_cache/",
        ".mypy_cache/",
        ".ruff_cache/",
        "",
        "# Setup logs generated by this helper",
        "setup_logs/",
        "",
    ]

    existing = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    existing_lines = set(existing.splitlines())
    lines_to_add = []
    for rule in rules:
        if rule == "" or rule.startswith("#"):
            lines_to_add.append(rule)
        elif rule not in existing_lines:
            lines_to_add.append(rule)

    if not lines_to_add:
        logging.info(".gitignore already had required ignore rules.")
        print(".gitignore already had the required ignore rules.")
        return

    with gitignore.open("a", encoding="utf-8") as f:
        if existing and not existing.endswith("\n"):
            f.write("\n")
        f.write("\n# Added by project-setup-helper\n")
        f.write("\n".join(lines_to_add))
        f.write("\n")

    logging.info(".gitignore updated: %s", gitignore)
    print(f".gitignore updated:\n  {gitignore}")
