"""Create or update .gitignore for Python projects."""

from __future__ import annotations

import logging

from project_setup_helper.config import VENV_DIR_NAME
from project_setup_helper.paths import PROJECT_ROOT
from project_setup_helper.prompts import ask_yes_no


def ensure_gitignore() -> None:
    """Create or update .gitignore with Python/venv ignore rules."""
    gitignore = PROJECT_ROOT / ".gitignore"
    rules = [
        "# Python virtual environments",
        f"{VENV_DIR_NAME}/",
        "venv/",
        "env/",
        "ENV/",
        "",
        "# Python cache/build artifacts",
        "__pycache__/",
        "*.py[cod]",
        "*.egg-info/",
        "build/",
        "dist/",
        "",
        "# Test/type/lint caches",
        ".pytest_cache/",
        ".mypy_cache/",
        ".ruff_cache/",
        "",
        "# Setup logs generated by this helper",
        "setup_logs/",
        "",
    ]

    existing = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""

    print("\nChecking .gitignore.")
    if gitignore.exists():
        print(".gitignore already exists. Missing Python/venv ignore rules will be appended.")
    else:
        print(".gitignore does not exist. It will be created.")

    if not ask_yes_no("Create/update .gitignore now?", default=True):
        print("Skipping .gitignore update.")
        return

    lines_to_add = []
    existing_lines = set(existing.splitlines())

    for rule in rules:
        if rule == "" or rule.startswith("#"):
            lines_to_add.append(rule)
        elif rule not in existing_lines:
            lines_to_add.append(rule)

    if lines_to_add:
        with gitignore.open("a", encoding="utf-8") as f:
            if existing and not existing.endswith("\n"):
                f.write("\n")
            f.write("\n# Added by project_setup_helper\n")
            f.write("\n".join(lines_to_add))
            f.write("\n")

        logging.info(".gitignore updated: %s", gitignore)
        print(f".gitignore updated:\n  {gitignore}")
    else:
        logging.info(".gitignore already had required ignore rules.")
        print(".gitignore already had the required ignore rules.")
