"""Write pyproject.toml and generated package scaffold."""

from __future__ import annotations

import logging
import textwrap

from project_setup_helper.config import (
    DEPENDENCIES,
    DEV_DEPENDENCIES,
    PACKAGE_IMPORT_NAME,
    PROJECT_NAME,
    USE_SRC_LAYOUT,
)
from project_setup_helper.paths import PROJECT_ROOT
from project_setup_helper.prompts import ask_yes_no


def create_pyproject_toml(include_dev: bool) -> None:
    """Create a minimal pyproject.toml and package structure."""
    pyproject = PROJECT_ROOT / "pyproject.toml"

    if pyproject.exists():
        print("\npyproject.toml already exists.")
        if not ask_yes_no("Overwrite it?", default=False):
            logging.info("Keeping existing pyproject.toml.")
            return

    package_root = PROJECT_ROOT / "src" / PACKAGE_IMPORT_NAME if USE_SRC_LAYOUT else PROJECT_ROOT / PACKAGE_IMPORT_NAME

    print("\nAbout to create pyproject.toml and package structure.")
    print(f"Project name:        {PROJECT_NAME}")
    print(f"Import package name: {PACKAGE_IMPORT_NAME}")
    print(f"Package folder:      {package_root}")

    if not ask_yes_no("Create pyproject.toml and package files now?", default=True):
        print("Skipping pyproject.toml/package creation.")
        return

    package_root.mkdir(parents=True, exist_ok=True)
    init_file = package_root / "__init__.py"
    cli_file = package_root / "cli.py"

    init_file.write_text('"""Project package."""\n\n__version__ = "0.1.0"\n', encoding="utf-8")
    cli_file.write_text(
        textwrap.dedent(
            f'''\
            """Command-line interface for {PROJECT_NAME}."""

            import argparse


            def main() -> None:
                """Run the command-line program."""
                parser = argparse.ArgumentParser(
                    description="Example command generated by the setup helper."
                )
                parser.add_argument(
                    "name",
                    nargs="?",
                    default="World",
                    help="Name to greet.",
                )

                args = parser.parse_args()
                print(f"Hello {{args.name}}!")


            if __name__ == "__main__":
                main()
            '''
        ),
        encoding="utf-8",
    )

    dependency_lines = ",\n".join(f'    "{dep}"' for dep in DEPENDENCIES)

    optional_dev_block = ""
    if include_dev:
        dev_lines = ",\n".join(f'    "{dep}"' for dep in DEV_DEPENDENCIES)
        optional_dev_block = f"""

[project.optional-dependencies]
dev = [
{dev_lines}
]
"""

    setuptools_block = ""
    if USE_SRC_LAYOUT:
        setuptools_block = """
[tool.setuptools.packages.find]
where = ["src"]
"""

    pyproject.write_text(
        textwrap.dedent(
            f"""\
            [build-system]
            requires = ["setuptools>=68"]
            build-backend = "setuptools.build_meta"

            [project]
            name = "{PROJECT_NAME}"
            version = "0.1.0"
            description = "Example Python project configured by interactive setup helper."
            requires-python = ">=3.10"
            dependencies = [
            {dependency_lines}
            ]

            [project.scripts]
            {PROJECT_NAME} = "{PACKAGE_IMPORT_NAME}.cli:main"
            """
        )
        + optional_dev_block
        + setuptools_block,
        encoding="utf-8",
    )

    logging.info("Wrote pyproject.toml.")
    logging.info("Created package folder: %s", package_root)
    print(f"Wrote:\n  {pyproject}")
    print(f"Created package folder:\n  {package_root}")
