"""Write local setup notes after the helper runs."""

from __future__ import annotations

import logging
import textwrap
from datetime import datetime

from project_setup_helper.config import PROJECT_STYLE, TARGET_OS
from project_setup_helper.os_detect import is_apple_silicon, is_macos
from project_setup_helper.paths import LOG_FILE, PROJECT_ROOT
from project_setup_helper.prompts import ask_yes_no
from project_setup_helper.venv_tools import get_activation_command, get_venv_python_path


def get_macos_notes_section() -> str:
    """Return macOS notes for SETUP_NOTES.md."""
    if TARGET_OS != "macos_linux":
        return ""

    return textwrap.dedent(
        """\

        ## macOS Apple Silicon: Homebrew Python

        Apple's system Python usually lives here:

        ```text
        /usr/bin/python3
        ```

        For development on Apple Silicon Macs, it is usually better to install
        Python using Homebrew:

        ```bash
        brew install python
        ```

        Homebrew's Python usually lives here:

        ```text
        /opt/homebrew/bin/python3
        ```

        Verify which Python your shell finds first:

        ```bash
        which -a python3
        python3 --version
        ```

        If `/usr/bin/python3` appears before `/opt/homebrew/bin/python3`, add
        Homebrew to the front of your PATH:

        ```bash
        echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zprofile
        source ~/.zprofile
        ```

        Then verify again:

        ```bash
        which python3
        python3 --version
        ```
        """
    )


def write_local_notes() -> None:
    """Write a small local note file summarizing commands."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    notes = PROJECT_ROOT / f"SETUP_NOTES_{timestamp}.md"

    print(f"\nAbout to write {notes.name}.")
    if not ask_yes_no("Write setup notes now?", default=True):
        print(f"Skipping {notes.name}.")
        return

    notes.write_text(
        textwrap.dedent(
            f"""\
            # Local Setup Notes

            Generated by `project-setup-helper`.

            Generated at: {timestamp}

            ## Activate the virtual environment

            ```bash
            {get_activation_command()}
            ```

            ## Project style

            Selected style:

            ```text
            {PROJECT_STYLE}
            ```

            ## Virtual environment Python

            The virtual environment Python should be located at:

            ```text
            {get_venv_python_path()}
            ```

            Verify it with:

            ```bash
            {get_venv_python_path()} --version
            ```
            """
        )
        + get_macos_notes_section(),
        encoding="utf-8",
    )

    logging.info("Wrote %s.", notes.name)
    print(f"Wrote:\n  {notes}")


def print_final_summary() -> None:
    """Print final setup summary."""
    print("\nSetup complete.")
    print(f"Log file:\n  {LOG_FILE}")

    print("\nTo activate your environment, run:")
    print(f"  {get_activation_command()}")

    print("\nTo verify the venv Python, run:")
    print(f"  {get_venv_python_path()} --version")

    if TARGET_OS == "macos_linux" and is_macos() and is_apple_silicon():
        print("\nFor macOS Apple Silicon, also verify your shell Python:")
        print("  which -a python3")
        print("  python3 --version")
