"""Example script generated by project-setup-helper."""


def main() -> None:
    """Run the example script."""
    print("Hello from your requirements.txt project!")


if __name__ == "__main__":
    main()
