"""Write local setup notes after the helper runs."""

from __future__ import annotations

import logging
import textwrap

from project_setup_helper.config import ProjectConfig
from project_setup_helper.os_detect import is_apple_silicon, is_macos
from project_setup_helper.paths import timestamp
from project_setup_helper.prompts import ask_yes_no
from project_setup_helper.venv_tools import get_activation_command, get_venv_python_path


def get_macos_notes_section() -> str:
    """Return macOS notes for SETUP_NOTES.md."""
    if not (is_macos() and is_apple_silicon()):
        return ""
    return textwrap.dedent(
        """\

        ## macOS Apple Silicon: Homebrew Python

        Apple's system Python usually lives here:

        ```text
        /usr/bin/python3
        ```

        For development on Apple Silicon Macs, it is usually better to install
        Python using Homebrew:

        ```bash
        brew install python
        ```

        Homebrew's Python usually lives here:

        ```text
        /opt/homebrew/bin/python3
        ```

        Verify which Python your shell finds first:

        ```bash
        which -a python3
        python3 --version
        ```
        """
    )


def write_local_notes(config: ProjectConfig) -> None:
    """Write a small local note file summarizing commands."""
    stamp = timestamp()
    notes = config.project_root / f"SETUP_NOTES_{stamp}.md"

    print(f"\nAbout to write {notes.name}.")
    if not ask_yes_no("Write setup notes now?", default=True):
        print(f"Skipping {notes.name}.")
        return

    notes.write_text(
        textwrap.dedent(
            f"""\
            # Local Setup Notes

            Generated by `project-setup-helper`.

            Generated at: {stamp}

            ## Project

            ```text
            {config.project_name}
            ```

            Project root:

            ```text
            {config.project_root}
            ```

            Project type:

            ```text
            {config.project_type}
            ```

            ## Python and pip

            Minimum Python requirement:

            ```text
            >= {config.minimum_python_version}
            ```

            Python interpreter used to create the virtual environment:

            ```text
            {config.python_interpreter}
            ```

            Pip target during setup:

            ```text
            {"pip==" + config.pip_version if config.pip_version else "latest pip"}
            ```

            ## Activate the virtual environment

            ```bash
            {get_activation_command(config)}
            ```

            ## Virtual environment Python

            The virtual environment Python should be located at:

            ```text
            {get_venv_python_path(config)}
            ```

            Verify it with:

            ```bash
            {get_venv_python_path(config)} --version
            ```
            """
        )
        + get_macos_notes_section(),
        encoding="utf-8",
    )

    logging.info("Wrote %s.", notes.name)
    print(f"Wrote:\n  {notes}")


def print_final_summary(config: ProjectConfig, log_file) -> None:
    """Print final setup summary."""
    print("\nSetup complete.")
    print(f"Project root:\n  {config.project_root}")
    print(f"Log file:\n  {log_file}")

    print("\nTo activate your environment, run:")
    print(f"  {get_activation_command(config)}")

    print("\nTo verify the venv Python and pip, run:")
    print(f"  {get_venv_python_path(config)} --version")
    print(f"  {get_venv_python_path(config)} -m pip --version")

    if config.uses_pyproject:
        print("\nTry the generated command after activation:")
        print(f"  {config.project_name} Demetrius")
        print("\nOr run the module directly:")
        print(f"  python -m {config.package_name} Demetrius")
