"""Generate pyproject.toml package project files."""

from __future__ import annotations

import logging
import textwrap

from project_setup_helper.config import DEPENDENCIES, DEV_DEPENDENCIES, ProjectConfig


def create_pyproject_package(config: ProjectConfig) -> None:
    """Create a minimal pyproject.toml package scaffold."""
    package_root = config.project_root / "src" / config.package_name
    tests_root = config.project_root / "tests"
    package_root.mkdir(parents=True, exist_ok=True)
    tests_root.mkdir(parents=True, exist_ok=True)

    (package_root / "__init__.py").write_text(
        f'"""{config.project_name} package."""\n\n__version__ = "0.1.0"\n',
        encoding="utf-8",
    )
    (package_root / "__main__.py").write_text(
        textwrap.dedent(
            f'''\
            """Run {config.project_name} as a module."""

            from {config.package_name}.cli import main


            if __name__ == "__main__":
                main()
            '''
        ),
        encoding="utf-8",
    )
    (package_root / "cli.py").write_text(
        textwrap.dedent(
            f'''\
            """Command-line interface for {config.project_name}."""

            import argparse


            def main() -> None:
                """Run the command-line program."""
                parser = argparse.ArgumentParser(
                    description="Example command generated by project-setup-helper."
                )
                parser.add_argument(
                    "name",
                    nargs="?",
                    default="World",
                    help="Name to greet.",
                )

                args = parser.parse_args()
                print(f"Hello {{args.name}}!")


            if __name__ == "__main__":
                main()
            '''
        ),
        encoding="utf-8",
    )

    (tests_root / "test_cli.py").write_text(
        textwrap.dedent(
            f'''\
            """Basic import test for the generated package."""

            import {config.package_name}


            def test_version_exists() -> None:
                assert {config.package_name}.__version__ == "0.1.0"
            '''
        ),
        encoding="utf-8",
    )

    dependency_lines = ",\n".join(f'    "{dep}"' for dep in DEPENDENCIES)
    optional_dev_block = ""
    if config.include_dev_tools:
        dev_lines = ",\n".join(f'    "{dep}"' for dep in DEV_DEPENDENCIES)
        optional_dev_block = f"""

[project.optional-dependencies]
dev = [
{dev_lines}
]
"""

    (config.project_root / "pyproject.toml").write_text(
        textwrap.dedent(
            f"""\
            [build-system]
            requires = ["setuptools>=68"]
            build-backend = "setuptools.build_meta"

            [project]
            name = "{config.project_name}"
            version = "0.1.0"
            description = "Example Python package generated by project-setup-helper."
            requires-python = ">=3.10"
            dependencies = [
            {dependency_lines}
            ]

            [project.scripts]
            {config.project_name} = "{config.package_name}.cli:main"
            """
        )
        + optional_dev_block
        + textwrap.dedent(
            """

            [tool.setuptools.packages.find]
            where = ["src"]
            """
        ),
        encoding="utf-8",
    )

    (config.project_root / "README.md").write_text(
        textwrap.dedent(
            f"""\
            # {config.project_name}

            This is an installable Python package that uses `pyproject.toml` and the `src/` layout.

            ## Distribution name vs import name

            The install/distribution name is:

            ```text
            {config.project_name}
            ```

            The Python import package name is:

            ```python
            import {config.package_name}
            ```

            ## Activate the virtual environment

            ```bash
            source .venv/bin/activate
            ```

            On Windows:

            ```powershell
            .venv\\Scripts\\activate
            ```

            ## Install in editable mode

            ```bash
            pip install -e .
            ```

            If you included development tools:

            ```bash
            pip install -e ".[dev]"
            ```

            ## Run

            ```bash
            {config.project_name} Demetrius
            python -m {config.package_name} Demetrius
            ```
            """
        ),
        encoding="utf-8",
    )

    logging.info("Created pyproject package files in %s", config.project_root)
    print(f"Wrote pyproject package files in:\n  {config.project_root}")
