"""Generate requirements.txt style project files."""

from __future__ import annotations

import logging
import textwrap

from project_setup_helper.config import DEPENDENCIES, DEV_DEPENDENCIES, ProjectConfig


def create_requirements_project(config: ProjectConfig) -> None:
    """Create files for a simple requirements.txt project."""
    requirements = config.project_root / "requirements.txt"
    requirements.write_text("\n".join(DEPENDENCIES) + "\n", encoding="utf-8")

    main_py = config.project_root / "main.py"
    main_py.write_text(
        textwrap.dedent(
            '''\
            """Example script generated by project-setup-helper."""


            def main() -> None:
                """Run the example script."""
                print("Hello from your requirements.txt project!")


            if __name__ == "__main__":
                main()
            '''
        ),
        encoding="utf-8",
    )

    if config.include_dev_tools:
        dev_file = config.project_root / "requirements-dev.txt"
        dev_file.write_text("\n".join(["-r requirements.txt", "", *DEV_DEPENDENCIES]) + "\n", encoding="utf-8")

    readme = config.project_root / "README.md"
    readme.write_text(
        textwrap.dedent(
            f"""\
            # {config.project_name}

            This is a simple Python project that uses `requirements.txt`.

            ## Activate the virtual environment

            ```bash
            source .venv/bin/activate
            ```

            On Windows:

            ```powershell
            .venv\\Scripts\\activate
            ```

            ## Install dependencies

            ```bash
            pip install -r requirements.txt
            ```

            If you included development tools:

            ```bash
            pip install -r requirements-dev.txt
            ```

            ## Run

            ```bash
            python main.py
            ```
            """
        ),
        encoding="utf-8",
    )

    logging.info("Created requirements project files in %s", config.project_root)
    print(f"Wrote requirements project files in:\n  {config.project_root}")
